export const color = {
    BLUE_PRIMARY: '#0786FB',
    BLUE_SECONDARY: '#E6F3FF',
    WHITE_PRIMARY: '#FFFFFF',
    WHITE_SECONDARY: '#F8F9FD',
    BLACK: '#1E2339',
    GRAY_PRIMARY: '#B5BEC6',
    RED_PRIMARY:'#F7284A',
    GREEN:'#0DCD94',
}